In [1]:
#OOPs 

In [2]:
def CeltoFer(c):
    f = (c*9/5)+32
    return f

In [3]:
CeltoFer(10)

50.0

In [4]:
class CeltoFer:
    def __init__(self,c):
        self.c = c
    def ctof(self):
        f =(self.c*9/5)+32
        print(f)

In [9]:
c1 = CeltoFer(10)
c1.ctof()
c2 = CeltoFer(20)
c2.ctof()

50.0
68.0


In [10]:
list1 = [1,2,3,4,5]

In [11]:
print(type(list1))

<class 'list'>


In [30]:
class Employee:
    company = 'Deloitte'
    def __init__(self,eid,ename,esal,eloc,company):
        self.eid = eid
        self.ename = ename
        self.esal = esal
        self.eloc = eloc
        self.company=company
        
    def display(self):
        print('The employee id is: ', self.eid)
        print('The employee name is: ', self.ename)
        print('The employee salary is: ', self.esal)
        print('The employee location is: ', self.eloc)
        print('You company is', Employee.company)
        
    def tax_calc(self):
        if self.esal<=2500:
            print('The total tax you have to pay is: ', self.esal*0.00)
        elif self.esal>2500 and self.esal<=5000:
            print('The total tax you have to pay is: ', self.esal*0.05)
        elif self.esal>5000 and self.esal<=7500:
            print('The total tax you have to pay is: ', self.esal*0.10)
        else:
            print('The total tax you have to pay is: ', self.esal*0.20)
            
    def bonus_calc(self):
        if self.eloc=='Gurgaon':
            print('The total bonus you will get is: ', self.esal*0.10)
        else:
            print('The total bonus you will get is: ', self.esal*0.20)

In [31]:
e1 = Employee(1,'Rahul',10000,'Gurgaon','TCS')
e1.display()
e1.tax_calc()
e1.bonus_calc()

The employee id is:  1
The employee name is:  Rahul
The employee salary is:  10000
The employee location is:  Gurgaon
You company is Deloitte
The total tax you have to pay is:  2000.0
The total bonus you will get is:  1000.0


In [32]:
Employee.company

'Deloitte'

In [33]:
e1.company

'TCS'

In [ ]:
#Class - as a calculator 
#Class - Area and perimeter of a circle
#Class - Small banking system 

In [34]:
#Numpy

In [35]:
import numpy as np

In [36]:
np.__version__

'1.20.3'

In [37]:
sales = [3453,2311,2342,1211]
profit = [432,112,332,123]

In [38]:
profit/sales

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [39]:
sales_array = np.array(sales)

In [40]:
profit_array = np.array(profit)

In [43]:
type(sales_array)

numpy.ndarray

In [44]:
type(profit_array)

numpy.ndarray

In [45]:
profit_array/sales_array

array([0.1251086 , 0.04846387, 0.14175918, 0.10156895])

In [72]:
list1 = [True]
type(list1[0])

bool

In [73]:
array1 = np.array(list1)

In [74]:
type(array1[0])

numpy.bool_

In [75]:
array1

array([ True])

In [78]:
sales*3

[3453, 2311, 2342, 1211, 3453, 2311, 2342, 1211, 3453, 2311, 2342, 1211]

In [79]:
sales_array*3

array([10359,  6933,  7026,  3633])

In [80]:
sales_us = [3454,2333,2112,2121]
sales_eu = [4322,2232,2222,2322]
sales_jp = [4323,2122,1433,1222]

In [82]:
sales_matrix = np.array([sales_us,sales_eu,sales_jp])

In [83]:
sales_matrix

array([[3454, 2333, 2112, 2121],
       [4322, 2232, 2222, 2322],
       [4323, 2122, 1433, 1222]])

In [84]:
sales_matrix[2,2]

1433

In [85]:
sales_matrix[1:3,1:3]

array([[2232, 2222],
       [2122, 1433]])

In [86]:
profit_us = [344,333,112,221]
profit_eu = [422,232,222,322]
profit_jp = [323,122,133,222]

In [87]:
profit_matrix = np.array([profit_us,profit_eu,profit_jp])

In [90]:
profit_matrix.shape

(3, 4)

In [91]:
sales_matrix.shape

(3, 4)

In [92]:
profit_matrix/sales_matrix

array([[0.09959467, 0.14273468, 0.0530303 , 0.10419613],
       [0.09763998, 0.10394265, 0.09990999, 0.13867356],
       [0.07471663, 0.05749293, 0.09281228, 0.18166939]])

In [93]:
profit_matrix

array([[344, 333, 112, 221],
       [422, 232, 222, 322],
       [323, 122, 133, 222]])

In [94]:
sales_matrix

array([[3454, 2333, 2112, 2121],
       [4322, 2232, 2222, 2322],
       [4323, 2122, 1433, 1222]])

In [95]:
sales_matrix.T

array([[3454, 4322, 4323],
       [2333, 2232, 2122],
       [2112, 2222, 1433],
       [2121, 2322, 1222]])

In [97]:
np.mean(sales_matrix)

2518.1666666666665

In [101]:
sales_matrix

array([[3454, 2333, 2112, 2121],
       [4322, 2232, 2222, 2322],
       [4323, 2122, 1433, 1222]])

In [99]:
np.mean(sales_matrix,axis=1)

array([2505. , 2774.5, 2275. ])

In [100]:
np.mean(sales_matrix,axis=0)

array([4033.        , 2229.        , 1922.33333333, 1888.33333333])

In [103]:
sales_matrix[np.where(sales_matrix<2000)]

array([1433, 1222])

In [104]:
np.where(sales_matrix<2000)

(array([2, 2], dtype=int64), array([2, 3], dtype=int64))

In [106]:
#Pandas
import pandas as pd

In [119]:
stu_details = {'sid':[1,2,3,4,5], 'sname':['A','B','C','D','E'], 'sregion':['N','S','S','E','W']}
stu_marks = {'s_id':[1,2,3,4,6], 'ssub':['Py','R','Tab','Py','Py'], 'smarks':[21,21,11,21,43]}

In [120]:
stu_details

{'sid': [1, 2, 3, 4, 5],
 'sname': ['A', 'B', 'C', 'D', 'E'],
 'sregion': ['N', 'S', 'S', 'E', 'W']}

In [121]:
stu_marks

{'s_id': [1, 2, 3, 4, 6],
 'ssub': ['Py', 'R', 'Tab', 'Py', 'Py'],
 'smarks': [21, 21, 11, 21, 43]}

In [122]:
df1 = pd.DataFrame(stu_details)

In [124]:
df1

sid sname sregion
0    1     A       N
1    2     B       S
2    3     C       S
3    4     D       E
4    5     E       W

In [123]:
df2 = pd.DataFrame(stu_marks)

In [125]:
df2

s_id ssub  smarks
0     1   Py      21
1     2    R      21
2     3  Tab      11
3     4   Py      21
4     6   Py      43

In [127]:
pd.merge(df1,df2,left_on='sid',right_on='s_id',how='inner')

sid sname sregion  s_id ssub  smarks
0    1     A       N     1   Py      21
1    2     B       S     2    R      21
2    3     C       S     3  Tab      11
3    4     D       E     4   Py      21

In [128]:
pd.merge(df1,df2,left_on='sid',right_on='s_id',how='left')

sid sname sregion  s_id ssub  smarks
0    1     A       N   1.0   Py    21.0
1    2     B       S   2.0    R    21.0
2    3     C       S   3.0  Tab    11.0
3    4     D       E   4.0   Py    21.0
4    5     E       W   NaN  NaN     NaN

In [129]:
pd.merge(df1,df2,left_on='sid',right_on='s_id',how='right')

sid sname sregion  s_id ssub  smarks
0  1.0     A       N     1   Py      21
1  2.0     B       S     2    R      21
2  3.0     C       S     3  Tab      11
3  4.0     D       E     4   Py      21
4  NaN   NaN     NaN     6   Py      43

In [130]:
pd.merge(pd.merge(df1,df2,left_on='sid',right_on='s_id',how='outer'),df3)

sid sname sregion  s_id ssub  smarks
0  1.0     A       N   1.0   Py    21.0
1  2.0     B       S   2.0    R    21.0
2  3.0     C       S   3.0  Tab    11.0
3  4.0     D       E   4.0   Py    21.0
4  5.0     E       W   NaN  NaN     NaN
5  NaN   NaN     NaN   6.0   Py    43.0

In [131]:
stu_details_US = {'sid':[1,2,3,4,5], 'sname':['A','B','C','D','E'], 'sregion':['N_US','S_US','S_US','E_US','W_US']}

In [132]:
stu_details_US

{'sid': [1, 2, 3, 4, 5],
 'sname': ['A', 'B', 'C', 'D', 'E'],
 'sregion': ['N_US', 'S_US', 'S_US', 'E_US', 'W_US']}

In [133]:
stu_details_IN = {'sid':[6,7,8,9,5], 'sname':['P','Q','R','S','E'], 'sregion':['N_IN','S_IN','S_IN','E_IN','W_US']}

In [134]:
stu_details_IN

{'sid': [6, 7, 8, 9, 5],
 'sname': ['P', 'Q', 'R', 'S', 'E'],
 'sregion': ['N_IN', 'S_IN', 'S_IN', 'E_IN', 'W_US']}

In [135]:
df1 = pd.DataFrame(stu_details_US)

In [136]:
df2 = pd.DataFrame(stu_details_IN)

In [137]:
df1

sid sname sregion
0    1     A    N_US
1    2     B    S_US
2    3     C    S_US
3    4     D    E_US
4    5     E    W_US

In [138]:
df2

sid sname sregion
0    6     P    N_IN
1    7     Q    S_IN
2    8     R    S_IN
3    9     S    E_IN
4    5     E    W_US

In [145]:
output = pd.concat([df1,df2],axis=0).reset_index().drop(columns='index').drop_duplicates()

In [149]:
output.to_excel('my_data_today.xlsx')

In [147]:
import os
os.getcwd()

'C:\\Users\\Rahul'

In [148]:
os.chdir('C:\\Users\\Rahul\\Desktop')